### PR TITLE
Real upgrade of Fedora

### PR DESCRIPTION
**Pull request by mkluson**

### CODE REVIEW

**Comment by psss** [comment]
Test now fails because reboot is not handled using the `tmt-reboot` script:

```
    out: :: [ 10:18:26 ] :: [   PASS   ] :: Download new Fedora packages (Expected 0, got 0)
    out: :: [ 10:18:26 ] :: [  BEGIN   ] :: start actual upgrade :: actually running 'dnf system-upgrade reboot'
Command returned '255'.
Append to file '/var/ARTIFACTS/work-fedora35to36E843C_/paths/fedora35to36/execute/data/tasks/upgrade/output.txt'.
00:02:41 /tasks/upgrade [2/4]
Copy '/var/ARTIFACTS/work-fedora35to36E843C_/paths/fedora35to36/execute/data/tasks/upgrade' from the guest to '/'.
Run command 'rsync -Rrz --links --safe-links --protect-args -e ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -i/etc/citool.d/id_rsa_artemis -S/tmp/tmpbsde9g36 root@18.218.197.254:/var/ARTIFACTS/work-fedora35to36E843C_/paths/fedora35to36/execute/data/tasks/upgrade /'.
environment: None
err: ssh: connect to host 18.218.197.254 port 22: Connection refused
```

The ssh connection is lost and `tmt` does not expect this. @mkluson, is it possible to instruct `dnf system-upgrade` to do whatever it needs to do just except the reboot itself? @lukaszachy, @FrNecas, any other ideas how to handle/workaround this?

**Comment by lukaszachy** [comment]
@psss Whole point of using dnf system-upgrade instead of simple dnf update -y is that you are rebooted into session when there shouldn't be any runtime problems with the update. 

Well, I can't think of anything better then having life check inside Guest which will re-try connection until success or timeout.
Of course configurable, so for "normal" tests, where ssh shouldn't drop it can be lower value by default but if execution is without ssh connection for hours it will set it accordingly.

**Comment by psss** [comment]
Yeah, the regular check and trying to reconnect could be a solution. I was also thinking about something like this:

    tmt-reboot --command "dnf system-upgrade reboot"

which would instruct `tmt` how to actually perform the reboot instead of the default method.

**Comment by psss** [comment]
@FrNecas, any quick thoughts about the solution for custom reboot command proposed above? Does it seems to be compatible with the way the `tmt-reboot` script is currently implemented?

**Comment by FrNecas** [comment]
@psss I think it's sort of close if we were to use `tmt-reboot --command "dnf system-upgrade reboot"` but it would not fully work. Yes, `tmt-reboot` would create the file signalling `tmt`, hey, I want to reboot, but `dnf system-upgrade reboot` would cause the test to hang, hence control will not be passed back to tmt's executor.

**Comment by psss** [comment]
My idea was that the `--command` parameter would not be executed by `tmt-reboot` itself but just handed over back to the executor which would call it using `guest.execute()` as it already does with `reboot` when there's no provision-specific method of performing the reboot.

https://github.com/teemtee/tmt/blob/5a011544e78ab2415731caf05984f90cb49a9792/tmt/steps/provision/__init__.py#L653

**Review by FrNecas — APPROVED** [review]
Merging, since I've already checked that it works with the upgrade plugin.

**Pull request merged**
